In [13]:
import numpy as np
# vector
x =np.arange(3,10,2)
print("x is:")
print(x)
y = np.arange(4,12,2)
print("y is:")
print(y)
dot_product_xy = np.dot(x,y)
print("dot_method_xy:")
print(dot_product)
# matrix
a =[[1,3], [5,6]]
print("a is:")
print(a)
b = [[2,3], [5,9]]
print("b is:")
print(b)

dot_product_ab = np.dot(a,b)
print("dot_method_ab:")
print(dot_product_ab)



x is:
[3 5 7 9]
y is:
[ 4  6  8 10]
dot_method_xy:
[[17 30]
 [40 69]]
a is:
[[1, 3], [5, 6]]
b is:
[[2, 3], [5, 9]]
dot_method_ab:
[[17 30]
 [40 69]]


In [14]:
a =[[1,3], [5,6]]
print("a is:")
print(a)
b = [[2,3], [5,9]]
print("b is:")
print(b)

outer_product_ab = np.outer(a,b)
print("dot_outer_ab:")
print(outer_product_ab)

a is:
[[1, 3], [5, 6]]
b is:
[[2, 3], [5, 9]]
dot_outer_ab:
[[ 2  3  5  9]
 [ 6  9 15 27]
 [10 15 25 45]
 [12 18 30 54]]


In [9]:
import numpy as np
a =[[2,3], [5,4]]
print("a is:")
print(a)
b = [[2,3], [5,9]]
print("b is:")
print(b)
multiply_product = np.multiply(a,b)
print("multiply product: ",multiply_product)
dot_product = np.dot(a,b)
print("dot_product: ",dot_product)
outer_product = np.outer(a,b)
print("outer_product: ",outer_product)
cross_product = np.cross(a,b)
print("cross_product is: ",cross_product)

a is:
[[2, 3], [5, 4]]
b is:
[[2, 3], [5, 9]]
multiply product:  [[ 4  9]
 [25 36]]
dot_product:  [[19 33]
 [30 51]]
outer_product:  [[ 4  6 10 18]
 [ 6  9 15 27]
 [10 15 25 45]
 [ 8 12 20 36]]
cross_product is:  [ 0 25]
